apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webook-ingress
spec:
  ingressClassName: nginx
  rules: #路由规则
    # 当 host 是 bai.webook.com 时，则命中这条
    - host: bai.webook.com
      http:
        paths:
          # 请求路径的前缀是 /
          # 将请求转发至 webook 服务上，端口为80
          - backend:
              service:
                name: webook
                port:
                  number: 80
            pathType: Prefix
            path: /